services:

  db:
    image: mariadb:10.4
    container_name: sqli_lab0_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SQLI_Exercise
      MYSQL_USER: sqli
      MYSQL_PASSWORD: sqli
    volumes:
      - ../DB/lab_0.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_lab0_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: sqli_lab0_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_lab0_data:
